import { useEffect, useRef, useState } from 'react'
import type { FormEvent, KeyboardEvent } from 'react'
import { Bot, LoaderCircle, Send, Sparkles, UserRound } from 'lucide-react'
import { askAssistant } from '../api'
import type { AiAssistantReply } from '../api'
import { translate } from '../i18n'
import type { LanguageCode } from '../i18n'

const suggestions = ['Help me prepare for my next appointment', 'Share general nutrition basics', 'What should I ask about gentle movement?']
type ChatMessage = { id: number; role: 'user' | 'assistant'; text: string; reply?: AiAssistantReply }

export function AiAssistantCard({ language }: { language: LanguageCode }) {
  const [question, setQuestion] = useState('')
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [streamedAnswer, setStreamedAnswer] = useState('')
  const [streamingReply, setStreamingReply] = useState<AiAssistantReply | null>(null)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const conversationEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!streamingReply) return
    const words = streamingReply.answer.split(/\s+/)
    let wordIndex = 0
    setStreamedAnswer('')
    const timer = window.setInterval(() => {
      wordIndex += 1
      setStreamedAnswer(words.slice(0, wordIndex).join(' '))
      if (wordIndex === words.length) {
        window.clearInterval(timer)
        setMessages((current) => [...current, { id: Date.now(), role: 'assistant', text: streamingReply.answer, reply: streamingReply }])
        setStreamingReply(null)
        setStreamedAnswer('')
      }
    }, 45)
    return () => window.clearInterval(timer)
  }, [streamingReply])

  useEffect(() => {
    conversationEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, streamedAnswer, loading])

  const submitQuestion = async (event: FormEvent) => {
    event.preventDefault()
    const trimmedQuestion = question.trim()
    const token = sessionStorage.getItem('maatricare-token')
    if (!trimmedQuestion || !token) return

    setError('')
    setLoading(true)
    setQuestion('')
    setMessages((current) => [...current, { id: Date.now(), role: 'user', text: trimmedQuestion }])
    try {
      setStreamingReply(await askAssistant(token, trimmedQuestion))
    } catch {
      setError('The assistant is unavailable right now. Please try again.')
      setQuestion(trimmedQuestion)
    } finally {
      setLoading(false)
    }
  }

  const handleKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault()
      if (!loading && !streamingReply && question.trim()) event.currentTarget.form?.requestSubmit()
    }
  }

  return (
    <section className="panel assistant-panel" aria-labelledby="assistant-title">
      <div className="panel-heading">
        <div>
          <p className="section-label">{translate(language, 'ai.label')}</p>
          <h2 id="assistant-title">{translate(language, 'ai.title')}</h2>
        </div>
        <span className="assistant-icon" aria-hidden="true"><Sparkles /></span>
      </div>
      <p className="panel-description">{translate(language, 'ai.description')}</p>
      <div className="assistant-conversation" aria-live="polite">
        {messages.length === 0 && !loading && !streamingReply && <div className="assistant-welcome"><Bot /><div><strong>{translate(language, 'ai.welcome')}</strong><span>{translate(language, 'ai.prompt')}</span></div></div>}
        {messages.map((message) => (
          <article className={`assistant-message ${message.role}`} key={message.id}>
            <span className="assistant-avatar" aria-hidden="true">{message.role === 'assistant' ? <Bot /> : <UserRound />}</span>
            <div><p>{message.text}</p>{message.reply && <small>{message.reply.source === 'LOCAL_OLLAMA' ? 'Generated by your local Ollama model.' : message.reply.source === 'LOCAL_MODEL_UNAVAILABLE' ? 'Local AI model is not running, so this is a starter guide response.' : 'Urgent safety guidance.'} {message.reply.safetyNote}</small>}</div>
          </article>
        ))}
        {loading && <article className="assistant-message assistant"><span className="assistant-avatar" aria-hidden="true"><Bot /></span><div className="assistant-typing" aria-label="MaatriCare is thinking"><i /><i /><i /></div></article>}
        {streamingReply && <article className={`assistant-message assistant${streamingReply.urgent ? ' urgent' : ''}`}><span className="assistant-avatar" aria-hidden="true"><Bot /></span><div><p>{streamedAnswer}<span className="assistant-cursor" /></p></div></article>}
        <div ref={conversationEndRef} />
      </div>
      <div className="assistant-suggestions" aria-label="Suggested questions">
        {suggestions.map((suggestion) => <button key={suggestion} type="button" disabled={loading || Boolean(streamingReply)} onClick={() => setQuestion(suggestion)}>{suggestion}</button>)}
      </div>
      <form className="assistant-form" onSubmit={submitQuestion}>
        <label className="sr-only" htmlFor="assistant-question">Your question</label>
        <textarea id="assistant-question" value={question} maxLength={600} onChange={(event) => setQuestion(event.target.value)} onKeyDown={handleKeyDown} placeholder={translate(language, 'ai.placeholder')} rows={2} />
        <button className="assistant-submit" type="submit" disabled={loading || Boolean(streamingReply) || !question.trim()} aria-label="Send question">
          {loading ? <LoaderCircle className="assistant-spinner" /> : <Send />}
        </button>
      </form>
      <p className="assistant-input-hint">{translate(language, 'ai.hint')}</p>
      {error && <p className="form-error" role="alert">{error}</p>}
    </section>
  )
}